//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDAREAS1
    {
        public GEDAREAS1()
        {
            this.GEDDIVISOES = new HashSet<GEDDIVISOES1>();
            this.GEDTIPOCLIENTE = new HashSet<GEDTIPOCLIENTE1>();
            this.GEDUNIDADEXAREAS = new HashSet<GEDUNIDADEXAREAS1>();
        }
    
        public decimal ARE_IDAREA { get; set; }
        public string ARE_DESCRICAO { get; set; }
        public Nullable<decimal> ARE_IDLABELGENERICO { get; set; }
    
        public virtual GEDLABELGENERICO1 GEDLABELGENERICO { get; set; }
        public virtual ICollection<GEDDIVISOES1> GEDDIVISOES { get; set; }
        public virtual ICollection<GEDTIPOCLIENTE1> GEDTIPOCLIENTE { get; set; }
        public virtual ICollection<GEDUNIDADEXAREAS1> GEDUNIDADEXAREAS { get; set; }
    }
}
