//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDAUDITORXPASSAGEM
    {
        public decimal ACL_IDAUDITORXPASSAGEM { get; set; }
        public decimal ACL_IDTIPOAUDITOR { get; set; }
        public decimal ACL_IDPASSAGEM { get; set; }
        public Nullable<System.DateTime> ACL_DATAHORAINI { get; set; }
        public Nullable<System.DateTime> ACL_DATAHORAFIM { get; set; }
        public string ACL_OBSERVACAO { get; set; }
        public Nullable<decimal> ACL_FLAGATIVO { get; set; }
    
        public virtual GEDTIPOAUDITOR GEDTIPOAUDITOR { get; set; }
    }
}
