//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDCONVENIO
    {
        public GEDCONVENIO()
        {
            this.GEDAUDITORXCONVENIO = new HashSet<GEDAUDITORXCONVENIO>();
            this.GEDPASSAGENS = new HashSet<GEDPASSAGENS>();
        }
    
        public decimal CON_IDCONVENIO { get; set; }
        public string CON_RAZAOSOCIAL { get; set; }
        public Nullable<decimal> CON_FLAGATIVO { get; set; }
        public string CON_CNPJ { get; set; }
        public string CON_CODCONVENIORP { get; set; }
    
        public virtual ICollection<GEDAUDITORXCONVENIO> GEDAUDITORXCONVENIO { get; set; }
        public virtual ICollection<GEDPASSAGENS> GEDPASSAGENS { get; set; }
    }
}
