//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDCONTROLECERTIFICADO1
    {
        public decimal CCD_IDCONTROLECERTIFICADO { get; set; }
        public decimal CCD_IDPADROESCERTIFICADO { get; set; }
        public decimal CCD_IDDOCUMENTO { get; set; }
        public decimal CCD_IDTIPOTOKEN { get; set; }
        public decimal CCD_IDTIPOCERTIFICADO { get; set; }
        public Nullable<System.DateTime> CCD_DATACERTIFICACAO { get; set; }
        public Nullable<System.DateTime> CCD_DATARECERTIFICACAO { get; set; }
        public string CCD_PROPRIETARIO { get; set; }
        public string CCD_CNPJ { get; set; }
        public string CCD_CPF { get; set; }
    
        public virtual GEDDOCUMENTOS1 GEDDOCUMENTOS { get; set; }
        public virtual GEDPADROESCERTIFICADO1 GEDPADROESCERTIFICADO { get; set; }
        public virtual GEDTIPOSCERTIFICADOS1 GEDTIPOSCERTIFICADOS { get; set; }
        public virtual GEDTIPOSTOKEN1 GEDTIPOSTOKEN { get; set; }
    }
}
