//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDCAPTIONCONTROL
    {
        public decimal GCC_ID { get; set; }
        public string GCC_FORMNAME { get; set; }
        public string GCC_CONTROLNAME { get; set; }
        public string GCC_CAPTION { get; set; }
    }
}
