//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDDIVISOES1
    {
        public GEDDIVISOES1()
        {
            this.GEDDIVISAOXGRUPOUSUARIO = new HashSet<GEDDIVISAOXGRUPOUSUARIO1>();
            this.GEDDOCUMENTOS = new HashSet<GEDDOCUMENTOS1>();
            this.GEDTIPOSDOCUMENTOS = new HashSet<GEDTIPOSDOCUMENTOS1>();
        }
    
        public decimal DIV_IDDIVISAO { get; set; }
        public Nullable<decimal> DIV_IDAREA { get; set; }
        public string DIV_DESCRICAO { get; set; }
        public string DIV_CODIGOREDUZIDO { get; set; }
        public Nullable<decimal> DIV_FLAGATIVO { get; set; }
        public Nullable<decimal> DIV_FLAGTIPOCLIENTE { get; set; }
    
        public virtual GEDAREAS1 GEDAREAS { get; set; }
        public virtual ICollection<GEDDIVISAOXGRUPOUSUARIO1> GEDDIVISAOXGRUPOUSUARIO { get; set; }
        public virtual ICollection<GEDDOCUMENTOS1> GEDDOCUMENTOS { get; set; }
        public virtual ICollection<GEDTIPOSDOCUMENTOS1> GEDTIPOSDOCUMENTOS { get; set; }
    }
}
