//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDDOCASSINANDO
    {
        public decimal DOA_IDDOCASSINANDO { get; set; }
        public Nullable<decimal> DOA_IDDOCUMENTO { get; set; }
        public Nullable<decimal> DOA_IDUSUARIOASSINA { get; set; }
        public Nullable<decimal> DOA_BLOQUEADO { get; set; }
        public Nullable<System.DateTime> DOA_DATACONSULTA { get; set; }
    }
}
