//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDDOCUMENTOVENCIDOTEMP
    {
        public decimal DVT_IDDOCUMENTOVENCIDOTEMP { get; set; }
        public string DVT_REGISTRO { get; set; }
        public string DVT_NOME { get; set; }
        public Nullable<decimal> DVT_IDDIVISAO { get; set; }
        public Nullable<decimal> DVT_IDTIPODOCUMENTO { get; set; }
        public Nullable<decimal> DVT_IDSUBTIPODOCUMENTO { get; set; }
        public Nullable<decimal> DVT_IDDOCUMENTO { get; set; }
        public Nullable<System.DateTime> DVT_DATAVENCIMENTO { get; set; }
        public Nullable<System.DateTime> DVT_DATAPROCESSAMETO { get; set; }
    }
}
