//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDFORMATOS1
    {
        public GEDFORMATOS1()
        {
            this.GEDDOCUMENTOS = new HashSet<GEDDOCUMENTOS1>();
        }
    
        public decimal FMT_IDFORMATO { get; set; }
        public string FMT_EXTENSAO { get; set; }
        public Nullable<decimal> FMT_FLAGATIVO { get; set; }
    
        public virtual ICollection<GEDDOCUMENTOS1> GEDDOCUMENTOS { get; set; }
    }
}
