//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDFUNCAOUSUARIO
    {
        public decimal FUS_IDFUNCAOUSUARIO { get; set; }
        public string FUS_DESCRICAO { get; set; }
        public string FUS_ICONE { get; set; }
        public Nullable<decimal> FUS_ORDEM { get; set; }
    }
}
