//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDFUNCAOXTIPOHIERARQUIA
    {
        public decimal FXT_IDFUNCXTPHIERAR { get; set; }
        public decimal FXT_IDTIPOHIERARQUIA { get; set; }
        public decimal FXT_IDFUNCAOUSUARIO { get; set; }
        public decimal FXT_FLAGATIVO { get; set; }
    }
}
