//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDGRUPOSUSUARIOS
    {
        public GEDGRUPOSUSUARIOS()
        {
            this.GEDDIVISAOXGRUPOUSUARIO = new HashSet<GEDDIVISAOXGRUPOUSUARIO>();
            this.GEDDOCUMENTOS = new HashSet<GEDDOCUMENTOS>();
            this.GEDPERFIS = new HashSet<GEDPERFIS>();
            this.GEDSUBTIPODOCXGRUPUSER = new HashSet<GEDSUBTIPODOCXGRUPUSER>();
            this.GEDUSUARIOS = new HashSet<GEDUSUARIOS>();
        }
    
        public decimal GRP_IDGRUPOUSUARIO { get; set; }
        public string GRP_DESCRICAO { get; set; }
        public Nullable<decimal> GRP_IDUNIDADE { get; set; }
        public Nullable<decimal> GRP_FLAGCONFIGSUBTIPODOC { get; set; }
        public Nullable<decimal> GRP_FLAGCONFIGDIVISAO { get; set; }
        public Nullable<decimal> GRP_FLAGPREFERENCIA { get; set; }
        public Nullable<decimal> GRP_FLAGSUPORTE { get; set; }
    
        public virtual ICollection<GEDDIVISAOXGRUPOUSUARIO> GEDDIVISAOXGRUPOUSUARIO { get; set; }
        public virtual ICollection<GEDDOCUMENTOS> GEDDOCUMENTOS { get; set; }
        public virtual GEDUNIDADES GEDUNIDADES { get; set; }
        public virtual ICollection<GEDPERFIS> GEDPERFIS { get; set; }
        public virtual ICollection<GEDSUBTIPODOCXGRUPUSER> GEDSUBTIPODOCXGRUPUSER { get; set; }
        public virtual ICollection<GEDUSUARIOS> GEDUSUARIOS { get; set; }
    }
}
