//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDGRUPOSUSUARIOS1
    {
        public GEDGRUPOSUSUARIOS1()
        {
            this.GEDDIVISAOXGRUPOUSUARIO = new HashSet<GEDDIVISAOXGRUPOUSUARIO1>();
            this.GEDDOCUMENTOS = new HashSet<GEDDOCUMENTOS1>();
            this.GEDPERFIS = new HashSet<GEDPERFIS1>();
            this.GEDSUBTIPODOCXGRUPUSER = new HashSet<GEDSUBTIPODOCXGRUPUSER1>();
            this.GEDUSUARIOS = new HashSet<GEDUSUARIOS1>();
        }
    
        public decimal GRP_IDGRUPOUSUARIO { get; set; }
        public string GRP_DESCRICAO { get; set; }
        public Nullable<decimal> GRP_IDUNIDADE { get; set; }
        public Nullable<decimal> GRP_FLAGCONFIGSUBTIPODOC { get; set; }
        public Nullable<decimal> GRP_FLAGCONFIGDIVISAO { get; set; }
        public Nullable<decimal> GRP_FLAGSUPORTE { get; set; }
        public Nullable<decimal> GRP_FLAGPREFERENCIA { get; set; }
    
        public virtual ICollection<GEDDIVISAOXGRUPOUSUARIO1> GEDDIVISAOXGRUPOUSUARIO { get; set; }
        public virtual ICollection<GEDDOCUMENTOS1> GEDDOCUMENTOS { get; set; }
        public virtual GEDUNIDADES1 GEDUNIDADES { get; set; }
        public virtual ICollection<GEDPERFIS1> GEDPERFIS { get; set; }
        public virtual ICollection<GEDSUBTIPODOCXGRUPUSER1> GEDSUBTIPODOCXGRUPUSER { get; set; }
        public virtual ICollection<GEDUSUARIOS1> GEDUSUARIOS { get; set; }
    }
}
