//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDHIERARQUIAXFUNCAO
    {
        public decimal HXF_IDHIERARQUIAXFUNCAO { get; set; }
        public decimal HXF_IDHIERARQUIA { get; set; }
        public decimal HXF_IDFUNCAOUSUARIO { get; set; }
        public decimal HXF_FLAGATIVO { get; set; }
        public Nullable<decimal> HXF_IDAREA { get; set; }
    }
}
