//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDHIERARQUIA
    {
        public decimal HIR_IDHIERARQUIA { get; set; }
        public decimal HIR_IDUSUARIO { get; set; }
        public decimal HIR_IDTIPOHIERARQUIA { get; set; }
        public decimal HIR_IDCOMPONENTE { get; set; }
        public decimal HIR_IDARRAY { get; set; }
        public string HIR_NAMECOMPONENT { get; set; }
    }
}
