//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDINTEGRACAOATENDIMENTO1
    {
        public decimal ING_IDINTEGRACAOATENDIMENTO { get; set; }
        public string ING_PASSAGEMEMERGENCIA { get; set; }
        public string ING_PASSAGEMINTERNACAO { get; set; }
        public Nullable<System.DateTime> ING_DATAPASSAGEMEMERGENCIA { get; set; }
        public Nullable<System.DateTime> ING_DATAPASSAGEMINTERNACAO { get; set; }
        public Nullable<System.DateTime> ING_DATACRIACAOOPERADOR { get; set; }
        public Nullable<decimal> ING_OPERADOR { get; set; }
        public string ING_NOMEOPERADOR { get; set; }
    }
}
