//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDLABELGENERICO
    {
        public GEDLABELGENERICO()
        {
            this.GEDAREAS = new HashSet<GEDAREAS>();
        }
    
        public decimal LAB_IDLABELGENERICO { get; set; }
        public string LAB_TITULOOPINIAO { get; set; }
        public string LAB_TIPOPRONTUARIO { get; set; }
        public string LAB_TIPODOCUMENTO { get; set; }
        public string LAB_SUBTIPODOCUMENTO { get; set; }
        public Nullable<decimal> LAB_FLAGCLIENTEPJ { get; set; }
        public Nullable<decimal> LAB_FLAGCLIENTEPF { get; set; }
        public Nullable<decimal> LAB_FLAGTDOSTIPOSDOC { get; set; }
        public Nullable<decimal> LAB_FLAGTELACLIENTEPF { get; set; }
        public Nullable<decimal> LAB_FLAGTELACLIENTEPJ { get; set; }
        public Nullable<decimal> LAB_FLAGTELACONVENIO { get; set; }
        public Nullable<decimal> LAB_FLAGTELAAUDITORXTIPODOC { get; set; }
        public Nullable<decimal> LAB_FLAGTELATIPOAUDITOR { get; set; }
        public Nullable<decimal> LAB_FLAGTPDOBRIGATORIO { get; set; }
        public Nullable<decimal> LAB_FLAGTPDCOBRANCA { get; set; }
        public Nullable<decimal> LAB_FLAGTPDGUARDA { get; set; }
        public Nullable<decimal> LAB_FLAGSTDCOBRANCA { get; set; }
        public Nullable<decimal> LAB_FLAGSTDGUARDA { get; set; }
        public Nullable<decimal> LAB_FLAGSTDOBRIGATORIO { get; set; }
        public Nullable<decimal> LAB_FLAGTPDVALIDADEDOCUMENTO { get; set; }
        public Nullable<decimal> LAB_FLAGTELAPASSAGEMPF { get; set; }
        public Nullable<decimal> LAB_FLAGTELAPASSAGEMPJ { get; set; }
        public Nullable<decimal> LAB_FLAGATIVARDATAPASSAGEMFIM { get; set; }
        public Nullable<decimal> LAB_FLAGCAMPOCONCLASSE { get; set; }
        public Nullable<decimal> LAB_FLAGLIBERATDSTPDOCS { get; set; }
        public Nullable<decimal> LAB_FLAGLIBERATDSSUBTPDOCS { get; set; }
        public Nullable<decimal> LAB_FLAGCAMPOSUSUARIO { get; set; }
        public Nullable<decimal> LAB_FLAGEXIBIRDOCNCERT { get; set; }
        public Nullable<decimal> LAB_FLAGATENDIMENTOINNERDOC { get; set; }
        public Nullable<decimal> LAB_FLAGEDICAODOCASSINADO { get; set; }
        public Nullable<decimal> LAB_FLAGPERIODODOCDIGITALIZADO { get; set; }
        public Nullable<decimal> LAB_FLAGDATADEMISSAO { get; set; }
        public Nullable<decimal> LAB_FLAGUNIDADE { get; set; }
    
        public virtual ICollection<GEDAREAS> GEDAREAS { get; set; }
    }
}
