//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDLOGALTERACAODOCUMENTO
    {
        public decimal LAD_IDLOGALTERACAODOCUMENTO { get; set; }
        public Nullable<System.DateTime> LAD_DATAALTERACAO { get; set; }
        public Nullable<decimal> LAD_IDUSUARIO { get; set; }
        public Nullable<decimal> LAD_IDDOCUMENTO { get; set; }
        public Nullable<decimal> LAD_IDPASSAGEM { get; set; }
        public string LAD_REGISTRO { get; set; }
        public string LAD_OBSERVACAO { get; set; }
    }
}
