//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDLOGERRO
    {
        public decimal LGE_IDLOGERRO { get; set; }
        public Nullable<System.DateTime> LGE_DATAHORA { get; set; }
        public Nullable<decimal> LGE_IDUSUARIO { get; set; }
        public Nullable<decimal> LGE_IDUNIDADE { get; set; }
        public string LGE_TOKEN { get; set; }
        public string LGE_CODOBJETO { get; set; }
        public string LGE_CLASSNAME { get; set; }
        public string LGE_FUNCTIONNAME { get; set; }
        public string LGE_ERROFULLNAME { get; set; }
        public string LGE_ERROMESSAGE { get; set; }
        public string LGE_ERROSTACKTRACE { get; set; }
        public string LGE_ERRODATA { get; set; }
    }
}
