//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDLOGPROCESSODOC1
    {
        public decimal LPD_IDLOGPROCESSODOC { get; set; }
        public decimal LPD_IDUSUARIO { get; set; }
        public decimal LPD_IDDOCUMENTO { get; set; }
        public decimal LPD_IDTIPODOCUMENTO { get; set; }
        public decimal LPD_IDSUBTIPODOCUMENTO { get; set; }
        public Nullable<System.DateTime> LPD_DATAHORA { get; set; }
        public string LPD_OBSERVACAOCONCLUSAO { get; set; }
        public Nullable<decimal> LPD_FLAGAPROVADO { get; set; }
        public Nullable<decimal> LPD_FLAGPENDENTEUPLOAD { get; set; }
        public Nullable<decimal> LPD_FLAGREVISADO { get; set; }
    }
}
