//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDLOG
    {
        public decimal LOG_IDLOG { get; set; }
        public decimal LOG_IDOBJETO { get; set; }
        public decimal LOG_IDUSUARIO { get; set; }
        public Nullable<decimal> LOG_IDUNIDADE { get; set; }
        public Nullable<System.DateTime> LOG_DATAHORA { get; set; }
        public string LOG_TOKEN { get; set; }
        public string LOG_IPESTACAO { get; set; }
        public string LOG_OBSERVACAO { get; set; }
        public string LOG_OBSERVACAOREGISTRO { get; set; }
        public string LOG_OBSERVACAOCLIENTE { get; set; }
        public string LOG_OBSERVACAOUSUARIO { get; set; }
        public Nullable<decimal> LOG_FLAGATIVO { get; set; }
    }
}
