//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDOCORRENCIAS1
    {
        public GEDOCORRENCIAS1()
        {
            this.GEDLOGOCORRENCIA = new HashSet<GEDLOGOCORRENCIA1>();
        }
    
        public decimal OCR_IDOCORRENCIA { get; set; }
        public decimal OCR_IDTIPODOCUMENTO { get; set; }
        public decimal OCR_IDTIPOOCORRENCIA { get; set; }
        public decimal OCR_IDSTATUSOCORRENCIA { get; set; }
        public decimal OCR_IDDOCUMENTO { get; set; }
        public decimal OCR_IDUSUARIOSOLICITANTE { get; set; }
        public Nullable<System.DateTime> OCR_DATASOLICITACAO { get; set; }
        public string OCR_OBSERVACAOSOLICITACAO { get; set; }
        public Nullable<decimal> OCR_IDUSUARIORESPONSAVEL { get; set; }
        public Nullable<System.DateTime> OCR_DATACONCLUSAO { get; set; }
        public string OCR_OBSERVACAOCONCLUSAO { get; set; }
        public Nullable<decimal> OCR_FLAGATIVO { get; set; }
        public Nullable<decimal> OCR_FLAGREPROVADO { get; set; }
        public Nullable<decimal> OCR_IDSUBTIPODOCUMENTO { get; set; }
    
        public virtual GEDDOCUMENTOS1 GEDDOCUMENTOS { get; set; }
        public virtual ICollection<GEDLOGOCORRENCIA1> GEDLOGOCORRENCIA { get; set; }
        public virtual GEDSTATUSOCORRENCIA1 GEDSTATUSOCORRENCIA { get; set; }
        public virtual GEDTIPOSDOCUMENTOS1 GEDTIPOSDOCUMENTOS { get; set; }
        public virtual GEDTIPOSOCORRENCIA1 GEDTIPOSOCORRENCIA { get; set; }
        public virtual GEDUSUARIOS1 GEDUSUARIOS { get; set; }
    }
}
