//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDOBJETOS1
    {
        public GEDOBJETOS1()
        {
            this.HELP_SUBMENU = new HashSet<HELP_SUBMENU>();
            this.GEDPERFISXOBJETOS = new HashSet<GEDPERFISXOBJETOS1>();
        }
    
        public decimal OBJ_IDOBJETO { get; set; }
        public Nullable<decimal> OBJ_IDMODULO { get; set; }
        public string OBJ_DESCRICAO { get; set; }
        public string OBJ_CODIGO { get; set; }
        public Nullable<decimal> OBJ_ORDEM { get; set; }
        public Nullable<decimal> OBJ_FLAGATIVO { get; set; }
    
        public virtual GEDMODULOS1 GEDMODULOS { get; set; }
        public virtual ICollection<HELP_SUBMENU> HELP_SUBMENU { get; set; }
        public virtual ICollection<GEDPERFISXOBJETOS1> GEDPERFISXOBJETOS { get; set; }
    }
}
