//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDOBJETOS
    {
        public GEDOBJETOS()
        {
            this.GEDPERFISXOBJETOS = new HashSet<GEDPERFISXOBJETOS>();
        }
    
        public decimal OBJ_IDOBJETO { get; set; }
        public Nullable<decimal> OBJ_IDMODULO { get; set; }
        public string OBJ_DESCRICAO { get; set; }
        public string OBJ_CODIGO { get; set; }
        public Nullable<decimal> OBJ_ORDEM { get; set; }
        public Nullable<decimal> OBJ_FLAGATIVO { get; set; }
    
        public virtual GEDMODULOS GEDMODULOS { get; set; }
        public virtual ICollection<GEDPERFISXOBJETOS> GEDPERFISXOBJETOS { get; set; }
    }
}
