//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDPERFISXOBJETOS
    {
        public decimal PXO_IDPERFILXOBJETO { get; set; }
        public decimal PXO_IDPERFIL { get; set; }
        public decimal PXO_IDOBJETO { get; set; }
    
        public virtual GEDOBJETOS GEDOBJETOS { get; set; }
        public virtual GEDPERFIS GEDPERFIS { get; set; }
    }
}
