//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDPASSAGENS1
    {
        public GEDPASSAGENS1()
        {
            this.GEDDOCUMENTOS = new HashSet<GEDDOCUMENTOS1>();
        }
    
        public decimal PAS_IDPASSAGEM { get; set; }
        public decimal PAS_IDUNIDADE { get; set; }
        public decimal PAS_IDCONVENIO { get; set; }
        public Nullable<System.DateTime> PAS_DATAHORAPASSAGEM { get; set; }
        public string PAS_CODIGOPASSAGEM { get; set; }
        public Nullable<decimal> PAS_FLAGCLIENTEPF { get; set; }
        public string PAS_REGISTRO { get; set; }
        public Nullable<System.DateTime> PAS_DATAHORAPASSAGEMFIM { get; set; }
        public string PAS_TIPOATENDIMENTO { get; set; }
    
        public virtual GEDCONVENIO1 GEDCONVENIO { get; set; }
        public virtual ICollection<GEDDOCUMENTOS1> GEDDOCUMENTOS { get; set; }
        public virtual GEDUNIDADES1 GEDUNIDADES { get; set; }
    }
}
