//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDPERFIS1
    {
        public GEDPERFIS1()
        {
            this.GEDPERFISXOBJETOS = new HashSet<GEDPERFISXOBJETOS1>();
            this.GEDPERFISXUSUARIOS = new HashSet<GEDPERFISXUSUARIOS1>();
        }
    
        public decimal PRF_IDPERFIL { get; set; }
        public Nullable<decimal> PRF_IDGRUPOUSUARIO { get; set; }
        public Nullable<decimal> PRF_IDUNIDADE { get; set; }
        public string PRF_DESCRICAO { get; set; }
    
        public virtual GEDGRUPOSUSUARIOS1 GEDGRUPOSUSUARIOS { get; set; }
        public virtual GEDUNIDADES1 GEDUNIDADES { get; set; }
        public virtual ICollection<GEDPERFISXOBJETOS1> GEDPERFISXOBJETOS { get; set; }
        public virtual ICollection<GEDPERFISXUSUARIOS1> GEDPERFISXUSUARIOS { get; set; }
    }
}
