//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDPESSOAS1
    {
        public GEDPESSOAS1()
        {
            this.GEDUSUARIOS = new HashSet<GEDUSUARIOS1>();
        }
    
        public decimal PES_IDPESSOA { get; set; }
        public string PES_NOME { get; set; }
        public string PES_NOMEMAE { get; set; }
        public string PES_NOMEPAI { get; set; }
        public string PES_CPF { get; set; }
        public string PES_RG { get; set; }
        public Nullable<System.DateTime> PES_DATANASCIMENTO { get; set; }
        public Nullable<decimal> PES_IDSEXO { get; set; }
        public string PES_TEL01 { get; set; }
        public string PES_TEL02 { get; set; }
        public string PES_CONTATO { get; set; }
        public string PES_EMAILPESSOAL { get; set; }
        public string PES_EMAILPROFISSIONAL { get; set; }
        public Nullable<decimal> PES_FLAGATIVO { get; set; }
        public string PES_OBSERVACAO { get; set; }
    
        public virtual GEDSEXOS1 GEDSEXOS { get; set; }
        public virtual ICollection<GEDUSUARIOS1> GEDUSUARIOS { get; set; }
    }
}
