//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDPERFISXUSUARIOS1
    {
        public decimal PXU_IDPERFILXUSUARIO { get; set; }
        public decimal PXU_IDPERFIL { get; set; }
        public decimal PXU_IDUSUARIO { get; set; }
        public Nullable<decimal> PXU_PERFILINICIAL { get; set; }
    
        public virtual GEDPERFIS1 GEDPERFIS { get; set; }
        public virtual GEDUSUARIOS1 GEDUSUARIOS { get; set; }
    }
}
