//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDSEXOS
    {
        public GEDSEXOS()
        {
            this.GEDCLIENTEPF = new HashSet<GEDCLIENTEPF>();
            this.GEDPESSOAS = new HashSet<GEDPESSOAS>();
        }
    
        public decimal SEX_IDSEXO { get; set; }
        public string SEX_DESCRICAO { get; set; }
        public string SEX_SIGLA { get; set; }
    
        public virtual ICollection<GEDCLIENTEPF> GEDCLIENTEPF { get; set; }
        public virtual ICollection<GEDPESSOAS> GEDPESSOAS { get; set; }
    }
}
