//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDSETORXGRUPOUSUARIO1
    {
        public decimal SXG_IDSETORXGRUPOUSUARIO { get; set; }
        public Nullable<decimal> SXG_IDSETOR { get; set; }
        public Nullable<decimal> SXG_IDGRUPOUSUARIO { get; set; }
        public Nullable<decimal> SXG_FLAGATIVO { get; set; }
    }
}
