//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDSUBTIPODOCXGRUPUSER1
    {
        public decimal TDG_IDSUBTIPODOCXGRUPUSER { get; set; }
        public Nullable<decimal> TDG_IDGRUPOUSUARIO { get; set; }
        public Nullable<decimal> TDG_IDSUBTIPODOCUMENTO { get; set; }
        public Nullable<decimal> TDG_FLAGATIVO { get; set; }
    
        public virtual GEDGRUPOSUSUARIOS1 GEDGRUPOSUSUARIOS { get; set; }
        public virtual GEDSUBTIPOSDOCUMENTOS1 GEDSUBTIPOSDOCUMENTOS { get; set; }
    }
}
