//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDTIPOSBUSCALOTES
    {
        public decimal TBL_ID { get; set; }
        public string TBL_DESCRICAO { get; set; }
        public Nullable<decimal> TBL_DEFAULT { get; set; }
    }
}
