//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDTIPOCONSELHO1
    {
        public decimal TPC_IDTIPOCONSELHO { get; set; }
        public string TPC_DESCRICAO { get; set; }
        public string TPC_SIGLA { get; set; }
    }
}
