//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDTIPOHIERARQUIA
    {
        public decimal TPH_IDTIPOHIERARQUIA { get; set; }
        public string TPH_DESCRICAO { get; set; }
        public decimal TPH_ORDEMHIERARQUIA { get; set; }
        public decimal TPH_FLAGATIVO { get; set; }
    }
}
