//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDTIPOSTOKEN1
    {
        public GEDTIPOSTOKEN1()
        {
            this.GEDCONTROLECERTIFICADO = new HashSet<GEDCONTROLECERTIFICADO1>();
        }
    
        public decimal TTK_IDTIPOTOKEN { get; set; }
        public string TTK_NOME { get; set; }
        public Nullable<decimal> TTK_FLAGATIVO { get; set; }
    
        public virtual ICollection<GEDCONTROLECERTIFICADO1> GEDCONTROLECERTIFICADO { get; set; }
    }
}
