//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDTIPOSATENDIMENTOS1
    {
        public decimal TIA_IDTIPOATENDIMENTO { get; set; }
        public string TIA_DESCRICAO { get; set; }
        public string TIA_FLAGATIVO { get; set; }
    }
}
