//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDTIPOSDOCUMENTOS1
    {
        public GEDTIPOSDOCUMENTOS1()
        {
            this.GEDDOCUMENTOS = new HashSet<GEDDOCUMENTOS1>();
            this.GEDOCORRENCIAS = new HashSet<GEDOCORRENCIAS1>();
            this.GEDSUBTIPOSDOCUMENTOS = new HashSet<GEDSUBTIPOSDOCUMENTOS1>();
        }
    
        public decimal TPD_IDTIPODOCUMENTO { get; set; }
        public decimal TPD_IDDIVISAO { get; set; }
        public string TPD_DESCRICAO { get; set; }
        public string TPD_CODIGOBARRA { get; set; }
        public Nullable<decimal> TPD_ORDEM { get; set; }
        public Nullable<decimal> TPD_FLAGSUBTIPO { get; set; }
        public Nullable<decimal> TPD_TEMPOVALIDADE { get; set; }
        public Nullable<decimal> TPD_OBRIGATORIO { get; set; }
        public Nullable<decimal> TPD_TEMPOGUARDA { get; set; }
        public Nullable<decimal> TPD_COBRANCADIAS { get; set; }
        public Nullable<decimal> TPD_FLAGIMPRESSAO { get; set; }
        public Nullable<decimal> TPD_FLAGTIPOCLIENTE { get; set; }
    
        public virtual GEDDIVISOES1 GEDDIVISOES { get; set; }
        public virtual ICollection<GEDDOCUMENTOS1> GEDDOCUMENTOS { get; set; }
        public virtual ICollection<GEDOCORRENCIAS1> GEDOCORRENCIAS { get; set; }
        public virtual ICollection<GEDSUBTIPOSDOCUMENTOS1> GEDSUBTIPOSDOCUMENTOS { get; set; }
    }
}
