//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDTIPOSBUSCALOTESPJ1
    {
        public decimal TPJ_ID { get; set; }
        public string TPJ_DESCRICAO { get; set; }
        public Nullable<decimal> TPJ_DEFAULT { get; set; }
    }
}
