//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDUNIDADEXAREAS
    {
        public GEDUNIDADEXAREAS()
        {
            this.GEDUSUARIOSXUNIDADESXAREAS = new HashSet<GEDUSUARIOSXUNIDADESXAREAS>();
        }
    
        public decimal UXA_IDUNIDADEXAREA { get; set; }
        public decimal UXA_IDUNIDADE { get; set; }
        public decimal UXA_IDAREA { get; set; }
    
        public virtual GEDAREAS GEDAREAS { get; set; }
        public virtual GEDUNIDADES GEDUNIDADES { get; set; }
        public virtual ICollection<GEDUSUARIOSXUNIDADESXAREAS> GEDUSUARIOSXUNIDADESXAREAS { get; set; }
    }
}
