//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDUSUARIOS
    {
        public GEDUSUARIOS()
        {
            this.GEDLOTESXUSUARIOS = new HashSet<GEDLOTESXUSUARIOS>();
            this.GEDOCORRENCIAS = new HashSet<GEDOCORRENCIAS>();
            this.GEDPERFISXUSUARIOS = new HashSet<GEDPERFISXUSUARIOS>();
            this.GEDTIPOAUDITOR = new HashSet<GEDTIPOAUDITOR>();
            this.GEDUSUARIOSXUNIDADESXAREAS = new HashSet<GEDUSUARIOSXUNIDADESXAREAS>();
        }
    
        public decimal USR_IDUSUARIO { get; set; }
        public Nullable<decimal> USR_IDGRUPOUSUARIO { get; set; }
        public Nullable<decimal> USR_IDPESSOA { get; set; }
        public string USR_LOGIN { get; set; }
        public string USR_SENHA { get; set; }
        public Nullable<decimal> USR_FLAGATIVO { get; set; }
        public Nullable<decimal> USR_FIRSTACCESS { get; set; }
        public Nullable<System.DateTime> USR_DATAHORACADASTRO { get; set; }
        public Nullable<System.DateTime> USR_DATAHORALASTLOGIN { get; set; }
        public string USR_OBSERVACAO { get; set; }
        public Nullable<decimal> USR_FLAGIMPRIMIR { get; set; }
        public Nullable<decimal> USR_FLAGIMPORTACAO { get; set; }
        public Nullable<decimal> USR_FLAGDIGITALIZACAO { get; set; }
        public Nullable<decimal> USR_FLAGASSINA { get; set; }
        public Nullable<decimal> USR_NIVELASSINA { get; set; }
        public string USR_SERIALNUMBERCERT { get; set; }
        public Nullable<decimal> USR_FLAGADMACS { get; set; }
        public Nullable<decimal> USR_FLAGPROCESSAMENTO { get; set; }
    
        public virtual GEDGRUPOSUSUARIOS GEDGRUPOSUSUARIOS { get; set; }
        public virtual ICollection<GEDLOTESXUSUARIOS> GEDLOTESXUSUARIOS { get; set; }
        public virtual ICollection<GEDOCORRENCIAS> GEDOCORRENCIAS { get; set; }
        public virtual ICollection<GEDPERFISXUSUARIOS> GEDPERFISXUSUARIOS { get; set; }
        public virtual GEDPESSOAS GEDPESSOAS { get; set; }
        public virtual ICollection<GEDTIPOAUDITOR> GEDTIPOAUDITOR { get; set; }
        public virtual ICollection<GEDUSUARIOSXUNIDADESXAREAS> GEDUSUARIOSXUNIDADESXAREAS { get; set; }
    }
}
