//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDURLSTORAGE
    {
        public decimal URS_IDURLSTORAGE { get; set; }
        public string URS_URLSTORAGE { get; set; }
        public Nullable<System.DateTime> URS_DATAHORAINI { get; set; }
        public Nullable<System.DateTime> URS_DATAHORAFIM { get; set; }
        public Nullable<decimal> URS_FLAGATIVO { get; set; }
    }
}
