//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDUNIDADES1
    {
        public GEDUNIDADES1()
        {
            this.GEDCLIENTEPF = new HashSet<GEDCLIENTEPF1>();
            this.GEDCLIENTEPJ = new HashSet<GEDCLIENTEPJ1>();
            this.GEDGLOBALSETTINGS = new HashSet<GEDGLOBALSETTINGS1>();
            this.GEDGRUPOSUSUARIOS = new HashSet<GEDGRUPOSUSUARIOS1>();
            this.GEDPASSAGENS = new HashSet<GEDPASSAGENS1>();
            this.GEDPERFIS = new HashSet<GEDPERFIS1>();
            this.GEDUNIDADEXAREAS = new HashSet<GEDUNIDADEXAREAS1>();
        }
    
        public decimal UNI_IDUNIDADE { get; set; }
        public string UNI_NOME { get; set; }
        public string UNI_DESCRICAO { get; set; }
        public string UNI_CNPJ { get; set; }
        public Nullable<System.DateTime> UNI_DATAHORAINI { get; set; }
        public string UNI_SITE { get; set; }
        public string UNI_OBSERVACAO { get; set; }
        public Nullable<decimal> UNI_FLAGATIVO { get; set; }
    
        public virtual ICollection<GEDCLIENTEPF1> GEDCLIENTEPF { get; set; }
        public virtual ICollection<GEDCLIENTEPJ1> GEDCLIENTEPJ { get; set; }
        public virtual ICollection<GEDGLOBALSETTINGS1> GEDGLOBALSETTINGS { get; set; }
        public virtual ICollection<GEDGRUPOSUSUARIOS1> GEDGRUPOSUSUARIOS { get; set; }
        public virtual ICollection<GEDPASSAGENS1> GEDPASSAGENS { get; set; }
        public virtual ICollection<GEDPERFIS1> GEDPERFIS { get; set; }
        public virtual ICollection<GEDUNIDADEXAREAS1> GEDUNIDADEXAREAS { get; set; }
    }
}
