//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDUNIDADES
    {
        public GEDUNIDADES()
        {
            this.GEDCLIENTEPF = new HashSet<GEDCLIENTEPF>();
            this.GEDCLIENTEPJ = new HashSet<GEDCLIENTEPJ>();
            this.GEDGLOBALSETTINGS = new HashSet<GEDGLOBALSETTINGS>();
            this.GEDGRUPOSUSUARIOS = new HashSet<GEDGRUPOSUSUARIOS>();
            this.GEDPASSAGENS = new HashSet<GEDPASSAGENS>();
            this.GEDPERFIS = new HashSet<GEDPERFIS>();
            this.GEDUNIDADEXAREAS = new HashSet<GEDUNIDADEXAREAS>();
        }
    
        public decimal UNI_IDUNIDADE { get; set; }
        public string UNI_NOME { get; set; }
        public string UNI_DESCRICAO { get; set; }
        public string UNI_CNPJ { get; set; }
        public Nullable<System.DateTime> UNI_DATAHORAINI { get; set; }
        public string UNI_SITE { get; set; }
        public string UNI_OBSERVACAO { get; set; }
        public Nullable<decimal> UNI_FLAGATIVO { get; set; }
    
        public virtual ICollection<GEDCLIENTEPF> GEDCLIENTEPF { get; set; }
        public virtual ICollection<GEDCLIENTEPJ> GEDCLIENTEPJ { get; set; }
        public virtual ICollection<GEDGLOBALSETTINGS> GEDGLOBALSETTINGS { get; set; }
        public virtual ICollection<GEDGRUPOSUSUARIOS> GEDGRUPOSUSUARIOS { get; set; }
        public virtual ICollection<GEDPASSAGENS> GEDPASSAGENS { get; set; }
        public virtual ICollection<GEDPERFIS> GEDPERFIS { get; set; }
        public virtual ICollection<GEDUNIDADEXAREAS> GEDUNIDADEXAREAS { get; set; }
    }
}
