//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDUSUARIOSXUNIDADESXAREAS1
    {
        public decimal UXU_IDUSUARIOXUNIDADEXAREA { get; set; }
        public Nullable<decimal> UXU_IDUNIDADEXAREA { get; set; }
        public Nullable<decimal> UXU_IDUSUARIO { get; set; }
    
        public virtual GEDUNIDADEXAREAS1 GEDUNIDADEXAREAS { get; set; }
        public virtual GEDUSUARIOS1 GEDUSUARIOS { get; set; }
    }
}
