//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSMinCapture.DataBase.ModelOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEDVOLUMES1
    {
        public GEDVOLUMES1()
        {
            this.GEDDOCUMENTOS = new HashSet<GEDDOCUMENTOS1>();
        }
    
        public decimal VOL_IDVOLUME { get; set; }
        public string VOL_DESCRICAO { get; set; }
    
        public virtual ICollection<GEDDOCUMENTOS1> GEDDOCUMENTOS { get; set; }
    }
}
