//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GED_PROC_CodigosBarras_Result:ICloneable
    {
        #region Primitive Properties
    
        [DisplayName("Código de Barras")]
        public string TPD_CODIGOBARRA
        {
            get;
            set;
        }

        [DisplayName("Divisão")]
        public string DIV_CODIGOREDUZIDO
        {
            get;
            set;
        }

        [DisplayName("Descrição")]
        public string TPD_DESCRICAO
        {
            get;
            set;
        }

        [Browsable(false)]
        public int TPD_IDDIVISAO
        {
            get;
            set;
        }

        [Browsable(false)]
        public int TPD_IDTIPODOCUMENTO
        {
            get;
            set;
        }

        [Browsable(false)]
        public Nullable<int> STD_IDSUBTIPOSDOCUMENTOS
        {
            get;
            set;
        }

        [Browsable(false)]
        public int STD_FLAGVENCIMENTOMANUAL
        {
            get;
            set;
        }

        [Browsable(false)]
        public int STD_MESVENCIMENTOANUAL
        {
            get;
            set;
        }

        [DisplayName("Validade")]
        public int TPD_TEMPOVALIDADE
        {
            get;
            set;
        }

        [Browsable(false)]
        public int REQUERDATAINICIOVALIDADE
        {
            get;
            set;
        }

        [DisplayName("Data Inicío Vigência")]
        public Nullable<System.DateTime> StartDateValidity
        {
            get;
            set;
        }

        [DisplayName("Data Validade")]
        public Nullable<System.DateTime> DateValidity
        {
            get;
            set;
        }

        #endregion

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
