//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDDivisoes
    {
        #region Primitive Properties
    
        public virtual int DIV_idDivisao
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DIV_idArea
        {
            get;
            set;
        }
    
        public virtual string DIV_descricao
        {
            get;
            set;
        }
    
        public virtual string DIV_codigoReduzido
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> DIV_flagAtivo
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<GEDDocumentos> GEDDocumentos
        {
            get
            {
                if (_gEDDocumentos == null)
                {
                    var newCollection = new FixupCollection<GEDDocumentos>();
                    newCollection.CollectionChanged += FixupGEDDocumentos;
                    _gEDDocumentos = newCollection;
                }
                return _gEDDocumentos;
            }
            set
            {
                if (!ReferenceEquals(_gEDDocumentos, value))
                {
                    var previousValue = _gEDDocumentos as FixupCollection<GEDDocumentos>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGEDDocumentos;
                    }
                    _gEDDocumentos = value;
                    var newValue = value as FixupCollection<GEDDocumentos>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGEDDocumentos;
                    }
                }
            }
        }
        private ICollection<GEDDocumentos> _gEDDocumentos;
    
        public virtual ICollection<GEDTiposDocumentos> GEDTiposDocumentos
        {
            get
            {
                if (_gEDTiposDocumentos == null)
                {
                    var newCollection = new FixupCollection<GEDTiposDocumentos>();
                    newCollection.CollectionChanged += FixupGEDTiposDocumentos;
                    _gEDTiposDocumentos = newCollection;
                }
                return _gEDTiposDocumentos;
            }
            set
            {
                if (!ReferenceEquals(_gEDTiposDocumentos, value))
                {
                    var previousValue = _gEDTiposDocumentos as FixupCollection<GEDTiposDocumentos>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGEDTiposDocumentos;
                    }
                    _gEDTiposDocumentos = value;
                    var newValue = value as FixupCollection<GEDTiposDocumentos>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGEDTiposDocumentos;
                    }
                }
            }
        }
        private ICollection<GEDTiposDocumentos> _gEDTiposDocumentos;

        #endregion

        #region Association Fixup
    
        private void FixupGEDDocumentos(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GEDDocumentos item in e.NewItems)
                {
                    item.GEDDivisoes = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GEDDocumentos item in e.OldItems)
                {
                    if (ReferenceEquals(item.GEDDivisoes, this))
                    {
                        item.GEDDivisoes = null;
                    }
                }
            }
        }
    
        private void FixupGEDTiposDocumentos(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GEDTiposDocumentos item in e.NewItems)
                {
                    item.GEDDivisoes = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GEDTiposDocumentos item in e.OldItems)
                {
                    if (ReferenceEquals(item.GEDDivisoes, this))
                    {
                        item.GEDDivisoes = null;
                    }
                }
            }
        }

        #endregion

    }
}
