//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDDocumentos
    {
        #region Primitive Properties
    
        public virtual int DOC_idDocumento
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_idVolume
        {
            get;
            set;
        }
    
        public virtual int DOC_idDivisao
        {
            get { return _dOC_idDivisao; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_dOC_idDivisao != value)
                    {
                        if (GEDDivisoes != null && GEDDivisoes.DIV_idDivisao != value)
                        {
                            GEDDivisoes = null;
                        }
                        _dOC_idDivisao = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _dOC_idDivisao;
    
        public virtual Nullable<int> DOC_idPassagem
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_idFormato
        {
            get { return _dOC_idFormato; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_dOC_idFormato != value)
                    {
                        if (GEDFormatos != null && GEDFormatos.FMT_idFormato != value)
                        {
                            GEDFormatos = null;
                        }
                        _dOC_idFormato = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _dOC_idFormato;
    
        public virtual Nullable<int> DOC_idTipoDocumento
        {
            get;
            set;
        }
    
        public virtual string DOC_path
        {
            get;
            set;
        }
    
        public virtual string DOC_nomeArquivo
        {
            get;
            set;
        }
    
        public virtual System.DateTime DOC_dataHoraCadastro
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> DOC_FlagCertificado
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_idSubTipoDocumento
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DOC_dataVencimento
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DOC_dataEmissao
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_tempoValidade
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> DOC_VencimentoResolvido
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_idUsuarioACSCapture
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_idUsuarioAssinaNivel1
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_idUsuarioAssinaNivel2
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_idUsuarioAssinaNivel3
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DOC_dataAssinaNivel1
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DOC_dataAssinaNivel2
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DOC_dataAssinaNivel3
        {
            get;
            set;
        }
    
        public virtual string DOC_p7s
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> DOC_flagAtivo
        {
            get;
            set;
        }
    
        public virtual string DOC_observacao
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_tipoCaptura
        {
            get;
            set;
        }
    
        public virtual string DOC_detail_cert
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DOC_Ordem_Visualizacao
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual GEDDivisoes GEDDivisoes
        {
            get { return _gEDDivisoes; }
            set
            {
                if (!ReferenceEquals(_gEDDivisoes, value))
                {
                    var previousValue = _gEDDivisoes;
                    _gEDDivisoes = value;
                    FixupGEDDivisoes(previousValue);
                }
            }
        }
        private GEDDivisoes _gEDDivisoes;
    
        public virtual GEDFormatos GEDFormatos
        {
            get { return _gEDFormatos; }
            set
            {
                if (!ReferenceEquals(_gEDFormatos, value))
                {
                    var previousValue = _gEDFormatos;
                    _gEDFormatos = value;
                    FixupGEDFormatos(previousValue);
                }
            }
        }
        private GEDFormatos _gEDFormatos;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupGEDDivisoes(GEDDivisoes previousValue)
        {
            if (previousValue != null && previousValue.GEDDocumentos.Contains(this))
            {
                previousValue.GEDDocumentos.Remove(this);
            }
    
            if (GEDDivisoes != null)
            {
                if (!GEDDivisoes.GEDDocumentos.Contains(this))
                {
                    GEDDivisoes.GEDDocumentos.Add(this);
                }
                if (DOC_idDivisao != GEDDivisoes.DIV_idDivisao)
                {
                    DOC_idDivisao = GEDDivisoes.DIV_idDivisao;
                }
            }
        }
    
        private void FixupGEDFormatos(GEDFormatos previousValue)
        {
            if (previousValue != null && previousValue.GEDDocumentos.Contains(this))
            {
                previousValue.GEDDocumentos.Remove(this);
            }
    
            if (GEDFormatos != null)
            {
                if (!GEDFormatos.GEDDocumentos.Contains(this))
                {
                    GEDFormatos.GEDDocumentos.Add(this);
                }
                if (DOC_idFormato != GEDFormatos.FMT_idFormato)
                {
                    DOC_idFormato = GEDFormatos.FMT_idFormato;
                }
            }
            else if (!_settingFK)
            {
                DOC_idFormato = null;
            }
        }

        #endregion

    }
}
