//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDFormatos
    {
        #region Primitive Properties
    
        public virtual int FMT_idFormato
        {
            get;
            set;
        }
    
        public virtual string FMT_extensao
        {
            get;
            set;
        }
    
        public virtual bool FMT_flagAtivo
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<GEDDocumentos> GEDDocumentos
        {
            get
            {
                if (_gEDDocumentos == null)
                {
                    var newCollection = new FixupCollection<GEDDocumentos>();
                    newCollection.CollectionChanged += FixupGEDDocumentos;
                    _gEDDocumentos = newCollection;
                }
                return _gEDDocumentos;
            }
            set
            {
                if (!ReferenceEquals(_gEDDocumentos, value))
                {
                    var previousValue = _gEDDocumentos as FixupCollection<GEDDocumentos>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGEDDocumentos;
                    }
                    _gEDDocumentos = value;
                    var newValue = value as FixupCollection<GEDDocumentos>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGEDDocumentos;
                    }
                }
            }
        }
        private ICollection<GEDDocumentos> _gEDDocumentos;

        #endregion

        #region Association Fixup
    
        private void FixupGEDDocumentos(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GEDDocumentos item in e.NewItems)
                {
                    item.GEDFormatos = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GEDDocumentos item in e.OldItems)
                {
                    if (ReferenceEquals(item.GEDFormatos, this))
                    {
                        item.GEDFormatos = null;
                    }
                }
            }
        }

        #endregion

    }
}
