//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDLotesXUsuarios
    {
        #region Primitive Properties
    
        public virtual int LTU_Id
        {
            get;
            set;
        }
    
        public virtual int LTU_IdUsuario
        {
            get { return _lTU_IdUsuario; }
            set
            {
                if (_lTU_IdUsuario != value)
                {
                    if (GEDUsuarios != null && GEDUsuarios.USR_idUsuario != value)
                    {
                        GEDUsuarios = null;
                    }
                    _lTU_IdUsuario = value;
                }
            }
        }
        private int _lTU_IdUsuario;
    
        public virtual string LTU_CodigoPassagem
        {
            get;
            set;
        }
    
        public virtual int LTU_IdStatusLote
        {
            get { return _lTU_IdStatusLote; }
            set
            {
                if (_lTU_IdStatusLote != value)
                {
                    if (GEDStatusLote != null && GEDStatusLote.STL_Id != value)
                    {
                        GEDStatusLote = null;
                    }
                    _lTU_IdStatusLote = value;
                }
            }
        }
        private int _lTU_IdStatusLote;
    
        public virtual System.DateTime LTU_Data
        {
            get;
            set;
        }
    
        public virtual string LTU_Observacao
        {
            get;
            set;
        }
    
        public virtual string LTU_PathImagens
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual GEDStatusLote GEDStatusLote
        {
            get { return _gEDStatusLote; }
            set
            {
                if (!ReferenceEquals(_gEDStatusLote, value))
                {
                    var previousValue = _gEDStatusLote;
                    _gEDStatusLote = value;
                    FixupGEDStatusLote(previousValue);
                }
            }
        }
        private GEDStatusLote _gEDStatusLote;
    
        public virtual GEDUsuarios GEDUsuarios
        {
            get { return _gEDUsuarios; }
            set
            {
                if (!ReferenceEquals(_gEDUsuarios, value))
                {
                    var previousValue = _gEDUsuarios;
                    _gEDUsuarios = value;
                    FixupGEDUsuarios(previousValue);
                }
            }
        }
        private GEDUsuarios _gEDUsuarios;

        #endregion

        #region Association Fixup
    
        private void FixupGEDStatusLote(GEDStatusLote previousValue)
        {
            if (previousValue != null && previousValue.GEDLotesXUsuarios.Contains(this))
            {
                previousValue.GEDLotesXUsuarios.Remove(this);
            }
    
            if (GEDStatusLote != null)
            {
                if (!GEDStatusLote.GEDLotesXUsuarios.Contains(this))
                {
                    GEDStatusLote.GEDLotesXUsuarios.Add(this);
                }
                if (LTU_IdStatusLote != GEDStatusLote.STL_Id)
                {
                    LTU_IdStatusLote = GEDStatusLote.STL_Id;
                }
            }
        }
    
        private void FixupGEDUsuarios(GEDUsuarios previousValue)
        {
            if (previousValue != null && previousValue.GEDLotesXUsuarios.Contains(this))
            {
                previousValue.GEDLotesXUsuarios.Remove(this);
            }
    
            if (GEDUsuarios != null)
            {
                if (!GEDUsuarios.GEDLotesXUsuarios.Contains(this))
                {
                    GEDUsuarios.GEDLotesXUsuarios.Add(this);
                }
                if (LTU_IdUsuario != GEDUsuarios.USR_idUsuario)
                {
                    LTU_IdUsuario = GEDUsuarios.USR_idUsuario;
                }
            }
        }

        #endregion

    }
}
