//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDPassagens
    {
        #region Primitive Properties
    
        public virtual int PAS_idPassagem
        {
            get;
            set;
        }
    
        public virtual int PAS_idUnidade
        {
            get;
            set;
        }
    
        public virtual int PAS_idConvenio
        {
            get;
            set;
        }
    
        public virtual System.DateTime PAS_dataHoraPassagem
        {
            get;
            set;
        }
    
        public virtual string PAS_codigoPassagem
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> PAS_flagClientePF
        {
            get;
            set;
        }
    
        public virtual string PAS_registro
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PAS_dataHoraPassagemFim
        {
            get;
            set;
        }

        #endregion

    }
}
