//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDPessoas
    {
        #region Primitive Properties
    
        public virtual int PES_idPessoa
        {
            get;
            set;
        }
    
        public virtual string PES_nome
        {
            get;
            set;
        }
    
        public virtual string PES_nomeMae
        {
            get;
            set;
        }
    
        public virtual string PES_nomePai
        {
            get;
            set;
        }
    
        public virtual string PES_cpf
        {
            get;
            set;
        }
    
        public virtual string PES_rg
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PES_dataNascimento
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PES_idSexo
        {
            get;
            set;
        }
    
        public virtual string PES_tel01
        {
            get;
            set;
        }
    
        public virtual string PES_tel02
        {
            get;
            set;
        }
    
        public virtual string PES_contato
        {
            get;
            set;
        }
    
        public virtual string PES_emailPessoal
        {
            get;
            set;
        }
    
        public virtual string PES_emailProfissional
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> PES_flagAtivo
        {
            get;
            set;
        }
    
        public virtual string PES_observacao
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<GEDUsuarios> GEDUsuarios
        {
            get
            {
                if (_gEDUsuarios == null)
                {
                    var newCollection = new FixupCollection<GEDUsuarios>();
                    newCollection.CollectionChanged += FixupGEDUsuarios;
                    _gEDUsuarios = newCollection;
                }
                return _gEDUsuarios;
            }
            set
            {
                if (!ReferenceEquals(_gEDUsuarios, value))
                {
                    var previousValue = _gEDUsuarios as FixupCollection<GEDUsuarios>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGEDUsuarios;
                    }
                    _gEDUsuarios = value;
                    var newValue = value as FixupCollection<GEDUsuarios>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGEDUsuarios;
                    }
                }
            }
        }
        private ICollection<GEDUsuarios> _gEDUsuarios;

        #endregion

        #region Association Fixup
    
        private void FixupGEDUsuarios(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GEDUsuarios item in e.NewItems)
                {
                    item.GEDPessoas = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GEDUsuarios item in e.OldItems)
                {
                    if (ReferenceEquals(item.GEDPessoas, this))
                    {
                        item.GEDPessoas = null;
                    }
                }
            }
        }

        #endregion

    }
}
