//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDSubTiposDocumentos
    {
        #region Primitive Properties
    
        public virtual int STD_idSubTiposDocumentos
        {
            get;
            set;
        }
    
        public virtual Nullable<int> STD_idTiposDocumentos
        {
            get;
            set;
        }
    
        public virtual string STD_descricao
        {
            get;
            set;
        }
    
        public virtual string STD_codigoBarra
        {
            get;
            set;
        }
    
        public virtual Nullable<int> STD_ordem
        {
            get;
            set;
        }
    
        public virtual Nullable<int> STD_tempoValidade
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> STD_obrigatorio
        {
            get;
            set;
        }
    
        public virtual Nullable<int> STD_tempoGuarda
        {
            get;
            set;
        }
    
        public virtual Nullable<int> STD_cobrancaDias
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> STD_flagVencimentoAnual
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> STD_flagVencimentoManual
        {
            get;
            set;
        }
    
        public virtual Nullable<int> STD_mesVencimentoAnual
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> STD_flagImpressao
        {
            get;
            set;
        }

        #endregion

    }
}
