//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDStatusLote
    {
        #region Primitive Properties
    
        public virtual int STL_Id
        {
            get;
            set;
        }
    
        public virtual string STL_Descricao
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<GEDLotesXUsuarios> GEDLotesXUsuarios
        {
            get
            {
                if (_gEDLotesXUsuarios == null)
                {
                    var newCollection = new FixupCollection<GEDLotesXUsuarios>();
                    newCollection.CollectionChanged += FixupGEDLotesXUsuarios;
                    _gEDLotesXUsuarios = newCollection;
                }
                return _gEDLotesXUsuarios;
            }
            set
            {
                if (!ReferenceEquals(_gEDLotesXUsuarios, value))
                {
                    var previousValue = _gEDLotesXUsuarios as FixupCollection<GEDLotesXUsuarios>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGEDLotesXUsuarios;
                    }
                    _gEDLotesXUsuarios = value;
                    var newValue = value as FixupCollection<GEDLotesXUsuarios>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGEDLotesXUsuarios;
                    }
                }
            }
        }
        private ICollection<GEDLotesXUsuarios> _gEDLotesXUsuarios;

        #endregion

        #region Association Fixup
    
        private void FixupGEDLotesXUsuarios(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GEDLotesXUsuarios item in e.NewItems)
                {
                    item.GEDStatusLote = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GEDLotesXUsuarios item in e.OldItems)
                {
                    if (ReferenceEquals(item.GEDStatusLote, this))
                    {
                        item.GEDStatusLote = null;
                    }
                }
            }
        }

        #endregion

    }
}
