//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDTiposDocumentos
    {
        #region Primitive Properties
    
        public virtual int TPD_idTipoDocumento
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TPD_idDivisao
        {
            get { return _tPD_idDivisao; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_tPD_idDivisao != value)
                    {
                        if (GEDDivisoes != null && GEDDivisoes.DIV_idDivisao != value)
                        {
                            GEDDivisoes = null;
                        }
                        _tPD_idDivisao = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _tPD_idDivisao;
    
        public virtual string TPD_descricao
        {
            get;
            set;
        }
    
        public virtual string TPD_codigoBarra
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TPD_ordem
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> TPD_flagSubtipo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TPD_tempoValidade
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> TPD_obrigatorio
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TPD_tempoGuarda
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TPD_cobrancaDias
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> TPD_flagImpressao
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual GEDDivisoes GEDDivisoes
        {
            get { return _gEDDivisoes; }
            set
            {
                if (!ReferenceEquals(_gEDDivisoes, value))
                {
                    var previousValue = _gEDDivisoes;
                    _gEDDivisoes = value;
                    FixupGEDDivisoes(previousValue);
                }
            }
        }
        private GEDDivisoes _gEDDivisoes;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupGEDDivisoes(GEDDivisoes previousValue)
        {
            if (previousValue != null && previousValue.GEDTiposDocumentos.Contains(this))
            {
                previousValue.GEDTiposDocumentos.Remove(this);
            }
    
            if (GEDDivisoes != null)
            {
                if (!GEDDivisoes.GEDTiposDocumentos.Contains(this))
                {
                    GEDDivisoes.GEDTiposDocumentos.Add(this);
                }
                if (TPD_idDivisao != GEDDivisoes.DIV_idDivisao)
                {
                    TPD_idDivisao = GEDDivisoes.DIV_idDivisao;
                }
            }
            else if (!_settingFK)
            {
                TPD_idDivisao = null;
            }
        }

        #endregion

    }
}
