//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ACSMinCapture.DataBase.Model
{
    public partial class GEDTiposBuscaLotes
    {
        #region Primitive Properties
    
        public virtual int TBL_Id
        {
            get;
            set;
        }
    
        public virtual string TBL_Descricao
        {
            get;
            set;
        }
    
        public virtual bool TBL_Default
        {
            get;
            set;
        }

        #endregion

    }
}
