//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionRecognizeLibraryTest.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCRDocEntities : DbContext
    {
        public OCRDocEntities()
            : base("name=OCRDocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OCR_Mapping> OCR_Mapping { get; set; }
        public DbSet<OCR_MappingXTypeDocument> OCR_MappingXTypeDocument { get; set; }
        public DbSet<OCR_MappingZone> OCR_MappingZone { get; set; }
        public DbSet<OCR_People> OCR_People { get; set; }
        public DbSet<OCR_TypeDocument> OCR_TypeDocument { get; set; }
    }
}
