//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionRecognizeLibraryTest.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCR_TypeDocument
    {
        public int TDC_Id { get; set; }
        public string TDC_Name { get; set; }
    }
}
