//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionRecognizeLibraryTest.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCR_MappingZone
    {
        public int ZON_Id { get; set; }
        public int ZON_MAP_Id { get; set; }
        public string ZON_Name { get; set; }
        public int ZON_Left { get; set; }
        public int ZON_Top { get; set; }
        public int ZON_Width { get; set; }
        public int ZON_Rigth { get; set; }
    }
}
