//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionRecognizeLibraryTest.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCR_People
    {
        public int PEO_Id { get; set; }
        public string PEO_Name { get; set; }
        public Nullable<System.DateTime> PEO_DateBirth { get; set; }
        public Nullable<decimal> PEO_CPF { get; set; }
        public string PEO_RG { get; set; }
    }
}
