//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionRecognizeLibraryTest.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCR_Mapping
    {
        public int MAP_Id { get; set; }
        public string MAP_Name { get; set; }
        public int MAP_Index { get; set; }
        public Nullable<int> MAP_Width { get; set; }
        public Nullable<int> MAP_Height { get; set; }
    }
}
